version: "3.8"

services:

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    command:
      "postgres -c 'max_connections=500'"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"

  api01:
    build: .
    volumes:
      - app-storage:/usr/src/app
    container_name: rinha-api01
    command:
      "rails server -b 0.0.0.0 -p 3001"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    hostname: rinha-api01
    depends_on:
      - db
    expose:
      - "3001"
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.0GB"

  api02:
    build: .
    volumes:
      - app-storage:/usr/src/app
    container_name: rinha-api02
    command:
      "rails server -b 0.0.0.0 -p 3002"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    hostname: rinha-api02
    depends_on:
      - db
    expose:
      - "3002"
    ports:
      - "3002:3002"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.0GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.1GB"

volumes:
  postgres_data: {}
  app-storage: {}

networks:
  default:
    driver: bridge
    name: rinha
